version: '3'
services:
##########################################
  nginx:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./data/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/websites:/usr/share/nginx/html  

# Let's Encrypt certificate auto-renewal
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"  
    networks:
            code-network:
                 aliases:
                   - www  
 
 # Let's Encrypt certificate auto-renewal
 # certbot:
 #   image: certbot/certbot
 #   volumes:
 #     - ./data/certbot/conf:/etc/letsencrypt
 #     - ./data/certbot/www:/var/www/certbot
 #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"



##########################################

  php:
    container_name: 'php-fpm'
    build: ./php_8.1.1/.
    volumes:
            - ./data/websites:/usr/share/nginx/html
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
            - code-network
    
#############################################

  mariadb:
    container_name: 'mysql'     
    image: mariadb:latest
    environment:
            MYSQL_ROOT_PASSWORD: 'root'
    ports:
            - "3306:3306"
    volumes:
            - ./data/mariadb/encryption:/etc/mysql/encryption
            - ./data/mariadb/my.cnf:/etc/mysql/my.cnf
            - ./data/mariadb/maria.conf.d:/etc/mysql/maria.conf.d
            - ./data/mariadb/certs:/etc/mysql/certs
    networks:
           code-network:
                aliases:
                   - mysql

###############################################
networks:
    code-network:
        driver: bridge
